@startuml

title __SRC's Class Diagram__\n

  namespace  {
    class GUI {
        + pword : String
        + uname : String
        ~ frame : JFrame
        ~ login : JButton
        ~ panel : JPanel
        ~ pass : JPasswordField
        ~ password : JLabel
        ~ space : JLabel
        ~ user : TextField
        ~ username : JLabel
        + GUI()
    }
  }
  

  namespace  {
    class Languages {
        ~ frame : JFrame
        ~ lang : String[]
        ~ language : JComboBox<String>
        ~ next : JButton
        ~ panel : JPanel
        ~ select : JLabel
        ~ space : JLabel
        + Languages()
    }
  }
  

  namespace  {
    class ReadingDatabase {
        + authenticate()
        + getContext()
        + getHints()
        + getSub()
        + gettext()
        - connet()
    }
  }
  

  namespace  {
    class Selection {
        ~ c : JLabel
        ~ context : JComboBox<String>
        ~ contexts : String[]
        ~ frame : JFrame
        ~ l : JLabel
        ~ level : JComboBox<String>
        ~ levels : String[]
        ~ next : JButton
        ~ panel : JPanel
        ~ s_contexts : String[]
        ~ sc : JLabel
        ~ space : JLabel
        ~ subcontext : JComboBox<String>
        + Selection()
    }
  }
  

  namespace  {
    class main {
        {static} + main()
    }
  }
  

  namespace  {
    class roleplay {
        ~ back : JButton
        ~ frame : JFrame
        ~ hint : JButton
        ~ hintarea : JTextArea
        ~ panel : JPanel
        ~ persons : JComboBox<String>
        ~ select : JLabel
        ~ t : JTextArea
        + roleplay()
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
